export const FETCHING_ALBUMS = "FETCHING_ALBUMS"
export const FETCHING_ALBUMS_SUCCESS= "FETCHING_ALBUMS_SUCCESS"
export const FETCHING_ALBUMS_FAIL = "FETCHING_ALBUMS_FAIL"

export const FETCHING_PHOTOS_BY_ALBUM_ID = "FETCHING_PHOTOS_BY_ALBUM_ID"
export const FETCHING_PHOTOS_BY_ALBUM_ID_SUCCESS= "FETCHING_PHOTOS_BY_ALBUM_ID_SUCCESS"
export const FETCHING_PHOTOS_BY_ALBUM_ID_FAIL = "FETCHING_PHOTOS_BY_ALBUM_ID_FAIL"


